### ISSUE TITLE
opening a snes rom turn up error

### ISSUE THREAD

**Issue by chensongchuan** [Pretz/SNesoid#5]
hello friends，afterr Deployment project on eclipse and running the project on my mobile phone，while I am opening a snes rom the software have appear error：
java.lang.UnsatisfiedLinkError: Couldn't load emu: findLibrary returned null
at java.lang.Runtime.loadLibrary(Runtime.java:365)
at java.lang.System.loadLibrary(System.java:535)
at com.androidemu.Emulator.createInstance(Emulator.java:46)
at com.androidemu.snes.EmulatorActivity.onCreate(EmulatorActivity.java:127)
at android.app.Activity.performCreate(Activity.java:5084)   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
at com.lbe.security.service.core.client.b.x.callActivityOnCreate(Unknown Source)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106)
at android.app.ActivityThread.access$600(ActivityThread.java:137)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4819)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)

**Comment by chensongchuan** [comment]
hello friends，afterr Deployment project on eclipse and running the project on my mobile phone，while I am opening a snes rom the software have appear error：
java.lang.UnsatisfiedLinkError: Couldn't load emu: findLibrary returned null
at java.lang.Runtime.loadLibrary(Runtime.java:365)
at java.lang.System.loadLibrary(System.java:535)
at com.androidemu.Emulator.createInstance(Emulator.java:46)
at com.androidemu.snes.EmulatorActivity.onCreate(EmulatorActivity.java:127)
at android.app.Activity.performCreate(Activity.java:5084) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
at com.lbe.security.service.core.client.b.x.callActivityOnCreate(Unknown Source)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106)
at android.app.ActivityThread.access$600(ActivityThread.java:137)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4819)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)at dalvik.system.NativeStart.main(Native Method)

**Comment by vuleanh** [comment]
Did you the answer for this problem? I am facing the same one. Can you give me the solution, please? Thank you
